//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wpf_db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Basket
    {
        public long id { get; set; }
        public Nullable<long> id_user { get; set; }
        public Nullable<long> id_goods { get; set; }
        public Nullable<bool> condition { get; set; }
    
        public virtual Goods Goods { get; set; }
        public virtual User User { get; set; }
    }
}
